In [ ]:
import numpy as np

intarr=np.array([1,2,3,4,5,6,7,8,9,10])
print(intarr)


[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
floatarr=np.array([26.6,4.6,7.11,27.4,10,6])
print(floatarr)

#to print type of array
print(type(floatarr))


[26.6   4.6   7.11 27.4  10.    6.  ]
<class 'numpy.ndarray'>


In [3]:
#type of the array
typarr=np.array([1,2,10,14.6],dtype='float32')
print(typarr)

#multidimensional array
multi_arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(multi_arr)

[ 1.   2.  10.  14.6]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [5]:

#array filled with zeros
arr=np.zeros(10,dtype=int)
print(arr)


[0 0 0 0 0 0 0 0 0 0]


In [7]:

#array filled with ones
onearr=np.ones([3,5],dtype=float)
print(onearr)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
#filling the array with our own value
arrfill=np.full((3, 5), 3.14,dtype=float)
print(arrfill)

seqarr=np.array([i for i in range(0,21,2)])
print(seqarr)
np.random.uniform(0,1,(3,3))

np. random. randint(0,10,(3,3))

np.ndarray(shape=(3),dtype=int)


[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
[ 0  2  4  6  8 10 12 14 16 18 20]


array([-973807568,        659,          0])