In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv('generic-food.csv', delimiter=',')
#list_of_rows = [list(row) for row in df.values]

#print(list_of_rows)
print(df)

         FOOD NAME                 SCIENTIFIC NAME             GROUP  \
0         Angelica                Angelica keiskei  Herbs and Spices   
1    Savoy cabbage  Brassica oleracea var. sabauda        Vegetables   
2    Silver linden                  Tilia argentea  Herbs and Spices   
3             Kiwi             Actinidia chinensis            Fruits   
4   Allium (Onion)                          Allium        Vegetables   
..             ...                             ...               ...   
94         Lettuce                  Lactuca sativa        Vegetables   
95       Grass pea                Lathyrus sativus            Pulses   
96       Sweet bay                  Laurus nobilis  Herbs and Spices   
97         Lentils                  Lens culinaris            Pulses   
98    Garden cress                Lepidium sativum        Vegetables   

                  SUB GROUP  
0                     Herbs  
1                  Cabbages  
2                     Herbs  
3           Tro

In [7]:
##arange()
import numpy as np
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [11]:
##linespace()
np.linspace(3, 6, num=4,endpoint=True,dtype=int)

np.linspace(3, 6, num=4,retstep=True)

(array([3., 4., 5., 6.]), 1.0)

In [3]:
##randint
import numpy as np
rand_int = np.random.randint(5,10)  
print("examplearray1\n",rand_int)

rand_int2 = np.random.randint(10,90,(4,5))
print( "examplearray2\n",rand_int2)

examplearray1
 7
examplearray2
 [[83 79 35 13 12]
 [69 29 23 53 77]
 [20 60 64 35 57]
 [11 19 29 75 65]]


In [22]:
##randn()-->normal distribution
randn1 = np.random.randn() 
print("randn1\n",randn1)

randn2 = np.random.randn(4,5) 
print( "randn2\n",randn2)

randn1
 0.43643848375837774
randn2
 [[-0.35666596  0.31097716 -1.15291338 -2.4653047   1.12170932]
 [-0.45692438 -1.03030266  0.17430166  0.23552303  1.20092908]
 [-0.29271407  0.58703004  0.20321053  1.66346897  0.22138174]
 [-1.07265513  0.9609842  -0.83227224  0.37163353 -1.50412296]]


In [23]:
##rand()-uniform distribution
rand = np.random.rand() 
print("rand\n", rand)

rand2 = np.random.rand(3,2) 
print("rand2\n", rand2)


rand
 0.24391071673913656
rand2
 [[0.02757444 0.62619292]
 [0.15606434 0.99457582]
 [0.44174046 0.84875468]]


In [27]:
##indexing in numpy array

a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a2[2,0])
print(a2[1])
print(a2[:,1])

7
[4 5 6]
[2 5 8]


In [31]:
##slicing in numpy array
a2 = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])

print(a2[1:2])
print(a2[1:,2:4])

[[15 16 17 18 19]]
[[17 18]
 [22 23]
 [27 28]]


In [6]:
##reshape and transpose
a = np.arange(6).reshape((3, 2))
print(a)

transp=np.transpose(a)
print("transpose\n",transp)

[[0 1]
 [2 3]
 [4 5]]
transpose
 [[0 2 4]
 [1 3 5]]


In [8]:
##to print the datatype and change the datatype of the numpy array
arr = np.array([10, 20, 30, 40, 50])
print(arr.dtype)

newtype=arr.astype('float32')
print(newtype)

int32
[10. 20. 30. 40. 50.]


In [17]:
##numpy array math
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
print(x + y) 

print(x - y)

print(x * y)

print(x / y)

print(np.sqrt(x))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[1.         1.41421356 1.73205081 2.        ]


In [23]:
##aggregate in numpy 
arr=np.array([1,2,3,4,5,6])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))


21
1
6
1.707825127659933


In [27]:
##acomparison in numpy
  
a = np.array([19, 12 ,87])
b = np.array([897, 97, 111])

equal = a==b
print(np.greater(a, b))

print(np.greater_equal(a, b))
  
print(np.less(a, b))
  
print(np.less_equal(a, b))

print(equal.all())

[False False False]
[False False False]
[ True  True  True]
[ True  True  True]
False


In [28]:
import numpy as np
import pandas as pd
df = pd.read_csv('generic-food.csv', delimiter=',')
list_of_rows = [list(row) for row in df.values]

print(list_of_rows)

##arange()
import numpy as np
arr=np.arange(1,10,2)
print(arr)
##linespace()
np.linspace(3, 6, num=4,endpoint=True,dtype=int)

np.linspace(3, 6, num=4,retstep=True)
##randint
import numpy as np
rand_int = np.random.randint(5,10)  
print("examplearray1\n",rand_int)

rand_int2 = np.random.randint(10,90,(4,5))
print( "examplearray2\n",rand_int2)
##randn()-->normal distribution
randn1 = np.random.randn() 
print("randn1\n",randn1)

randn2 = np.random.randn(4,5) 
print( "randn2\n",randn2)
##rand()-uniform distribution
rand = np.random.rand() 
print("rand\n", rand)

rand2 = np.random.rand(3,2) 
print("rand2\n", rand2)
##indexing in numpy array

a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a2[2,0])
print(a2[1])
print(a2[:,1])
##slicing in numpy array
a2 = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])

print(a2[1:2])
print(a2[1:,2:4])
##reshape and transpose
a = np.arange(6).reshape((3, 2))
print(a)

transp=np.transpose(a)
print("transpose\n",transp)
##to print the datatype and change the datatype of the numpy array
arr = np.array([10, 20, 30, 40, 50])
print(arr.dtype)

newtype=arr.astype('float32')
print(newtype)
##numpy array math
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
print(x + y) 

print(x - y)

print(x * y)

print(x / y)

print(np.sqrt(x))
##aggregate in numpy 
arr=np.array([1,2,3,4,5,6])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
##acomparison in numpy
  
a = np.array([19, 12 ,87])
b = np.array([897, 97, 111])

equal = a==b
print(np.greater(a, b))

print(np.greater_equal(a, b))
  
print(np.less(a, b))
  
print(np.less_equal(a, b))

print(equal.all())

[['Angelica', 'Angelica keiskei', 'Herbs and Spices', 'Herbs'], ['Savoy cabbage', 'Brassica oleracea var. sabauda', 'Vegetables', 'Cabbages'], ['Silver linden', 'Tilia argentea', 'Herbs and Spices', 'Herbs'], ['Kiwi', 'Actinidia chinensis', 'Fruits', 'Tropical fruits'], ['Allium (Onion)', 'Allium', 'Vegetables', 'Onion-family vegetables'], ['Garden onion', 'Allium cepa', 'Vegetables', 'Onion-family vegetables'], ['Leek', 'Allium porrum', 'Vegetables', 'Onion-family vegetables'], ['Garlic', 'Allium sativum', 'Herbs and Spices', 'Herbs'], ['Chives', 'Allium schoenoprasum', 'Herbs and Spices', 'Herbs'], ['Lemon verbena', 'Aloysia triphylla', 'Herbs and Spices', 'Herbs'], ['Cashew nut', 'Anacardium occidentale', 'Nuts', 'Nuts'], ['Pineapple', 'Ananas comosus', 'Fruits', 'Tropical fruits'], ['Dill', 'Anethum graveolens', 'Herbs and Spices', 'Herbs'], ['Custard apple', 'Annona reticulata', 'Fruits', 'Tropical fruits'], ['Wild celery', 'Apium graveolens', 'Herbs and Spices', 'Spices'], ['Pean